@electroapi.api_HostAddress = https://localhost:7220


GET {{electroapi.api_HostAddress}}/api/v1/order

###

POST {{electroapi.api_HostAddress}}/api/v1/order
Content-Type: application/json

{
  //Order
}

###

GET {{electroapi.api_HostAddress}}/api/v1/product

###
